name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          touch .env
          echo DB_HOST=${{ secrets.DB_HOST_PROD }} >> .env
          echo DB_USER=${{ secrets.DB_USER_PROD }} >> .env
          echo DB_PASS=${{ secrets.DB_PASS_PROD }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME_PROD }} >> .env
          cat .env

      - name: Deploy backend to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          env_file: ".env"

      - name: Run database migrations
        run: npm run migration:run
